# -*- coding: utf-8 -*-
"""stem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QAd1q3snLodTdQ03B2I_pS3Um8hb0tw9
"""

import tensorflow as tf

def conv(inputs, filters, kernel, stride, name):
  x = tf.keras.layers.Conv2D(filters, kernel, padding='same', strides=stride, use_bias=False, name=name+'/conv')(inputs)
  x = tf.keras.layers.BatchNormalization(name=name+'/bn')(x)
  return tf.keras.layers.ReLU(6.)(x)


def dconv(inputs, kernel, stride, name):
    x = tf.keras.layers.DepthwiseConv2D(kernel, strides=(stride, stride), depth_multiplier=1, padding='same', use_bias=False, name=name+'/sconv')(inputs)
    x = tf.keras.layers.BatchNormalization(name=name+'/bn')(x)
    return tf.keras.layers.ReLU(6.)(x)

def dsconv(x, filters, name, stride=1):
    x = dconv(x, 3,  stride=stride, name=name+'/sconv')
    x = conv(x, filters, 1, stride=1, name=name+'/conv')
    return x
    
def darkconv(inputs, filters, kernel, name):
  x = tf.keras.layers.Conv2D(filters, kernel,kernel_regularizer=tf.keras.regularizers.l2(5e-4), padding='same', name=name+'/conv')(inputs)
  x = tf.keras.layers.BatchNormalization(momentum=0.99, epsilon=1e-5, center=False, scale=True, name=name+'/bn')(x)
  x = tf.keras.layers.LeakyReLU(alpha=0.1)(x)
  return x

def mobilenet25(x):
    x     = conv(x, 8, (3,3), stride=2, name='genYOLOv2/stem/conv1')

    x     = dsconv(x, 16, name='genYOLOv2/stem/conv2')
    x     = dsconv(x, 32, stride=2, name='genYOLOv2/stem/conv3')

    x     = dsconv(x, 32, name='genYOLOv2/stem/conv4')
    x     = dsconv(x, 64, stride=2, name='genYOLOv2/stem/conv5')

    x     = dsconv(x, 64, name='genYOLOv2/stem/conv6')
    x     = dsconv(x, 128, stride=2, name='genYOLOv2/stem/conv7')
    x     = dsconv(x, 128, name='genYOLOv2/stem/conv8')
    x     = dsconv(x, 128, name='genYOLOv2/stem/conv9')
    x     = dsconv(x, 128, name='genYOLOv2/stem/conv10')
    x     = dsconv(x, 128, name='genYOLOv2/stem/conv11')
    x = p = dsconv(x, 128, name='genYOLOv2/stem/conv12')
    x     = dsconv(x, 256, stride=2, name='genYOLOv2/stem/conv13')
    x     = dsconv(x, 256, name='genYOLOv2/stem/conv14')
    return x,p