# -*- coding: utf-8 -*-
"""utils

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NfX3_vr2ZXuFRpLEUX7JxZuyEeE8GnM4
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install git+https://github.com/taehoonlee/tensornets.git

import tensorflow as tf
import numpy as np
from stem import *
from tensornets.references.yolo_utils import get_v2_boxes

bases = {}
labels_voc={1:'aeroplane',2:'bicycle',3:'bird',4:'boat',5:'bottle',6:'bus',7:'car',8:'cat',9:'chair',10:'cow',11:'diningtable',12:'dog',13:'horse',14:'motorbike',15:'person',16:'pottedplant',17:'sheep',18:'sofa',19:'train',20:'tvmonitor'}
bases['anchors'] =  [1.3221, 1.73145, 3.19275, 4.00944, 5.05587,
                                  8.09892, 9.47112, 4.84053, 11.2364, 10.0071]
bases.update({'num': 5})
bases.update({'classes':20, 'labels': labels_voc})

def model(inputs): 
  x, passthough=mobilenet25(inputs)

  x = darkconv(x, 1024, 3, name='genYOLOv2/conv7')
  x = darkconv(x, 1024, 3, name='genYOLOv2/conv8')

  p = darkconv(passthough, 64, 1, name='genYOLOv2/conv5a')
  p = tf.reshape(p,[-1, 13,13,256], name='flat5a')

  x = tf.concat([p, x], axis=3, name='concat')
  x = darkconv(x, 1024, 3, name='genYOLOv2/conv9')
  x = tf.keras.layers.Conv2D((bases['classes'] + 5) * 5, 1, kernel_regularizer=tf.keras.regularizers.l2(5e-4), padding='same', name='genYOLOv2/linear/conv')(x)
  x.aliases = []
  def get_boxes(*args, **kwargs):
      return get_v2_boxes(bases, *args, **kwargs)
  x.get_boxes = get_boxes

  return x